<dependency>
<groupId>com.sksamuel.elastic4s</groupId>
<artifactId>elastic4s-http_2.12</artifactId>
<version>5.4.10</version>
</dependency>
<dependency>
<groupId>com.sksamuel.elastic4s</groupId>
<artifactId>elastic4s-testkit_2.12</artifactId>
<version>5.4.10</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>com.sksamuel.elastic4s</groupId>
<artifactId>elastic4s-jackson_2.12</artifactId>
<version>5.4.10</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>com.sksamuel.exts</groupId>
<artifactId>exts_2.12</artifactId>
<version>1.44.0</version>
</dependency>
<dependency>
<groupId>org.typelevel</groupId>
<artifactId>cats_2.12</artifactId>
<version>0.9.0</version>
</dependency>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
<version>1.7.12</version>
</dependency>
<dependency>
<groupId>org.elasticsearch</groupId>
<artifactId>elasticsearch</artifactId>
<version>5.4.1</version>
</dependency>